import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { mkdtempSync, writeFileSync, mkdirSync, rmSync } from "fs";
import { tmpdir } from "os";
import path from "path";
import { analyzePlugins } from "../src/intel/plugins.js";

let dir: string;

beforeAll(() => {
  dir = mkdtempSync(path.join(tmpdir(), "rpgmv-plugins-"));
  mkdirSync(path.join(dir, "data"));
  mkdirSync(path.join(dir, "js", "plugins"), { recursive: true });

  writeFileSync(path.join(dir, "js", "plugins.js"), `// Generated by RPG Maker.
var $plugins =
[
{"name":"QuestSystem","status":true,"description":"Quest log","parameters":{"Max Quests":"50","Menu Label":"Quests"}},
{"name":"GhostPlugin","status":false,"description":"","parameters":{}}
];
`);

  writeFileSync(path.join(dir, "js", "plugins", "QuestSystem.js"), `/*:
 * @plugindesc v1.2 A full quest journal system
 * @author Jane Dev
 *
 * @param Max Quests
 * @desc Maximum tracked quests
 * @type number
 * @default 50
 *
 * @param Menu Label
 * @desc Label shown in the menu
 * @default Quests
 *
 * @command startQuest
 *
 * @help
 * Use the plugin command startQuest <id> to begin a quest.
 * Quests are stored in variables.
 */
(function(){})();
`);
  // GhostPlugin.js intentionally absent.
});

afterAll(() => rmSync(dir, { recursive: true, force: true }));

describe("analyzePlugins", () => {
  it("reads the plugin list from js/plugins.js", async () => {
    const r = await analyzePlugins(dir);
    expect(r.source).toBe("js/plugins.js");
    expect(r.total).toBe(2);
    expect(r.enabled).toBe(1);
  });

  it("fuses configured values with header metadata", async () => {
    const r = await analyzePlugins(dir);
    const quest = r.plugins.find((p) => p.name === "QuestSystem")!;
    expect(quest.status).toBe(true);
    expect(quest.author).toBe("Jane Dev");
    expect(quest.description).toBe("Quest log"); // configured value wins over @plugindesc
    expect(quest.params.map((p) => p.name)).toEqual(["Max Quests", "Menu Label"]);
    expect(quest.params[0].default).toBe("50");
    expect(quest.values["Max Quests"]).toBe("50");
    expect(quest.commands).toContain("startQuest");
    expect(quest.helpExcerpt).toContain("startQuest");
  });

  it("flags a configured plugin whose file is missing", async () => {
    const r = await analyzePlugins(dir);
    const ghost = r.plugins.find((p) => p.name === "GhostPlugin")!;
    expect(ghost.fileMissing).toBe(true);
  });

  it("returns an empty report when nothing is configured", async () => {
    const empty = mkdtempSync(path.join(tmpdir(), "rpgmv-noplugins-"));
    mkdirSync(path.join(empty, "data"));
    const r = await analyzePlugins(empty);
    expect(r.source).toBe("none");
    expect(r.total).toBe(0);
    rmSync(empty, { recursive: true, force: true });
  });
});
