#!/usr/bin/env node
/**
 * extract-engine.mjs — dev tool: distill RPG Maker MV's actual engine into
 * committed ground-truth at src/data/engineDefaults.ts, so the MCP's autotiler,
 * command builder and DB schemas match the real engine instead of guesswork.
 *
 * Reads from a RPG Maker MV install (NewData/ default project + js/ runtime):
 *   RPGMV_ENGINE_PATH env var, or the default Steam install path below.
 *
 * Run: node scripts/extract-engine.mjs
 */
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'fs';
import path from 'path';

const ROOT = process.env.RPGMV_ENGINE_PATH
  || '/home/diego/.local/share/Steam/steamapps/common/RPG Maker MV/NewData';
const CORE = path.join(ROOT, 'js', 'rpg_core.js');
const OBJ = path.join(ROOT, 'js', 'rpg_objects.js');
const DATA = path.join(ROOT, 'data');
const OUT = path.join(path.dirname(new URL(import.meta.url).pathname), '..', 'src', 'data', 'engineDefaults.ts');

if (!existsSync(CORE)) {
  console.error('Engine not found at', ROOT, '\nSet RPGMV_ENGINE_PATH to your RPG Maker MV NewData folder.');
  process.exit(1);
}

const core = readFileSync(CORE, 'utf8');

// --- autotile render tables (verbatim JS array literals) ---
function extractTable(name) {
  const start = core.indexOf('Tilemap.' + name + ' = [');
  if (start < 0) throw new Error('table not found: ' + name);
  const open = core.indexOf('[', start + ('Tilemap.' + name + ' = ').length);
  let depth = 0, i = open;
  for (; i < core.length; i++) {
    if (core[i] === '[') depth++;
    else if (core[i] === ']') { depth--; if (depth === 0) { i++; break; } }
  }
  const literal = core.slice(open, i);
  return JSON.parse(literal.replace(/\s+/g, '')); // pure number arrays -> valid JSON
}
const FLOOR = extractTable('FLOOR_AUTOTILE_TABLE');
const WALL = extractTable('WALL_AUTOTILE_TABLE');

// --- command param-name reference (code -> [param names]) from rpg_objects.js ---
const obj = readFileSync(OBJ, 'utf8');
const cmdCodes = [...obj.matchAll(/Game_Interpreter\.prototype\.command(\d+)\s*=/g)].map(m => Number(m[1]));
const COMMAND_CODES = [...new Set(cmdCodes)].sort((a, b) => a - b);

// --- canonical DB entry templates from the default project (NewData/data) ---
const ENTITY_FILES = {
  actors: 'Actors.json', classes: 'Classes.json', skills: 'Skills.json', items: 'Items.json',
  weapons: 'Weapons.json', armors: 'Armors.json', enemies: 'Enemies.json', states: 'States.json',
  troops: 'Troops.json', animations: 'Animations.json', tilesets: 'Tilesets.json', common_events: 'CommonEvents.json'
};
const TEMPLATES = {};
for (const [entity, file] of Object.entries(ENTITY_FILES)) {
  const p = path.join(DATA, file);
  if (!existsSync(p)) continue;
  const arr = JSON.parse(readFileSync(p, 'utf8'));
  const sample = arr.find(e => e && typeof e === 'object');
  if (!sample) continue;
  // a template = the sample with identity fields blanked, structural fields kept
  const t = JSON.parse(JSON.stringify(sample));
  if ('id' in t) t.id = 0;
  if ('name' in t) t.name = '';
  TEMPLATES[entity] = t;
}

const banner = `// AUTO-GENERATED by scripts/extract-engine.mjs from a real RPG Maker MV install.\n// Do not edit by hand. Ground truth for autotiling, commands and DB schemas.\n`;
const ts = banner +
  `export const FLOOR_AUTOTILE_TABLE = ${JSON.stringify(FLOOR)} as number[][][];\n` +
  `export const WALL_AUTOTILE_TABLE = ${JSON.stringify(WALL)} as number[][][];\n` +
  `export const ENGINE_COMMAND_CODES = ${JSON.stringify(COMMAND_CODES)} as number[];\n` +
  `export const DB_TEMPLATES: Record<string, any> = ${JSON.stringify(TEMPLATES, null, 0)};\n`;

writeFileSync(OUT, ts);
console.log('Wrote', OUT);
console.log('  FLOOR shapes:', FLOOR.length, '| WALL shapes:', WALL.length);
console.log('  command codes:', COMMAND_CODES.length);
console.log('  DB templates:', Object.keys(TEMPLATES).join(', '));
